#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-memcached
Version  : 1.58
Release  : 18
URL      : http://pypi.debian.net/python-memcached/python-memcached-1.58.tar.gz
Source0  : http://pypi.debian.net/python-memcached/python-memcached-1.58.tar.gz
Summary  : A Python memcached client library.
Group    : Development/Tools
License  : Python-2.0
Requires: python-memcached-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python

%description
[![Build
Status](https://travis-ci.org/linsomniac/python-memcached.svg)](https://travis-ci.org/linsomniac/python-memcached)

%package python
Summary: python components for the python-memcached package.
Group: Default
Requires: six-python

%description python
python components for the python-memcached package.


%prep
%setup -q -n python-memcached-1.58

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
